# Generated by Django 5.1 on 2024-08-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pdf_url',
            field=models.URLField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
